# Site settings
title: Fernando Teixeira
description: A minimalist personal website for sharing articles, talks, and projects
url: "https://teixeirafernando.github.io"
baseurl: ""
author:
  name: Fernando Teixeira
  email: fernandoadt1@gmail.com
  linkedin: fernandoadt
  github: teixeirafernando
  twitter: # Add your Twitter username here if you have one

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  articles:
    output: true
    permalink: /articles/:title/
  talks:
    output: true
    permalink: /talks/:title/
  projects:
    output: true
    permalink: /projects/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
