# Jekyll
theme: linkhub-jekyll-theme

# Site Configuration
name: Fernando Teixeira  # Name of your website
tagline: Links  # Set your preferred page title
description: Software Engineer in Test | Lead QA Engineer at Verivox # Also used as a meta description
favicon: assets/images/noto--technologist-medium-light-skin-tone.svg # Path / URL to the favicon of your website (e.g., 'assets/images/favicon.png')
logo: assets/images/new-profile.jpg # Path / URL to the logo (e.g., 'assets/images/logo.png')
url: https://teixeira-fernando.github.io # URL of your website
locale: en_DE # The value specifies the locale in which these tags are marked up. It follows the format `language_TERRITORY`.
ga4: G-L88Z5BTKF4 # Google Analytics 4 measurement ID (optional). Remove it if not needed.
image:
  path: assets/images/new-profile.jpg # Used for SEO
  type: png # File format of image. Change according to your image. Supported types: https://en.wikipedia.org/wiki/Media_type#Common_examples
  height: 200 # Pixels
  width: 192
  alt:  

# Verified Badge Configuration
badge: true  # Set to 'true' or 'false' to enable / disable the badge
icon: ri:verified-badge-fill  # Enter the icon name for the badge from Iconify Design (https://icon-sets.iconify.design/)
color: '#dfb221'  # Define the color of the badge
 
# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"    

# Exclude
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, CHANGELOG.md, Gemfile, LICENSE.txt, funding.yml, linkhub-jekyll-theme.gemspec]
