# Site settings
title: Fernando Teixeira
description: Personal website for sharing my articles, talks, and projects
favicon: assets/images/general/noto--technologist-medium-light-skin-tone.svg # Path / URL to the favicon of your website (e.g., 'assets/images/favicon.png')
url: "https://teixeirafernando.github.io"
locale: en_US # The value specifies the locale in which these tags are marked up. It follows the format `language_TERRITORY`.
author:
  name: Fernando Teixeira
  email: fernandoadt1@gmail.com
  linkedin: fernandoadt
  github: teixeirafernando

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  articles:
    output: true
    permalink: /articles/:title/
  talks:
    output: true
    permalink: /talks/:title/
  projects:
    output: true
    permalink: /projects/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
